[package]
name = "lineal"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["ellsphillips <@ellsphillips>"]
license = "MIT"
description = "Build elegent slide decks with Typst"
repository = "https://github.com/ellsphiillips/lineal"
keywords = ["typst", "touying", "slide", "theme", "template", "lecture", "presentation"]
categories = ["presentation"]
exclude = [".github/", "README.md"]
